### ISSUE TITLE
Exes and compiling

### ISSUE THREAD

**Issue by SzotsGabor** [JENebel/Cadabra#1]
Hi Joachim,

Exe files would be welcomed, not many are able to compile the sources.
Normally I don't have difficulties but this time I get this error message:

**error: linker `link.exe` not found
  |
  = note: program not found

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.**

I don't know how to install VS with the Visual C++ option. Any directions, please?

Gabor Szots,
CCRL testing group

**Comment by JENebel** [comment]
Hello Gabor, 
thank you very much for the interest!

Are you using Cargo to build? And are you able to compile other rust programs on your machine?

Please also note that Cadabra is very much in development and not finished. There is no search implemented yet, which means that it cannot play chess. Only the movegenerator is finished. So at the moment it can only run perft. When I have a more finished engine, I will provide executables.

I do though have another finished engine: [JENCE](https://github.com/JENebel/JENChessEngine), which I have just uploaded binaries for.

**Comment by SzotsGabor** [comment]
Now that's a surprise, I mean that it cannot play chess. Now I understand why it was not in releases , only in tags.

Otherwise yes, I use cargo build, the error message above is an output from that. Normally all goes well. Please note that I am not a programmer, I only learned some basics about compiling.

I'm going to keep an eye on Cadabra development.

**Comment by JENebel** [comment]
Allright, I appreciate it.

I believe that you need to install the c++ build tools for your rust compiler to work. The installer can be downloaded [here](https://visualstudio.microsoft.com/downloads/). I don't think you will be able to compile any rust programs, not just mine, without it.

**Comment by SzotsGabor** [comment]
> Allright, I appreciate it.
> 
> I believe that you need to install the c++ build tools for your rust compiler to work. The installer can be downloaded [here](https://visualstudio.microsoft.com/downloads/). I don't think you will be able to compile any rust programs, not just mine, without it.

I have compiled several Rust programs already. I don't remember ever having Visual Studio. But I may have had. Anyway, now I have installed VS and indeed I can compile your source now.

**Comment by SzotsGabor** [comment]
I am going to start a tournament with Cadabra in a couple of days. Most likely it will appear on next weeks's blitz list.

**Comment by JENebel** [comment]
Thank you very much. It is greatly appreciated!
