### ISSUE TITLE
Exes

### ISSUE THREAD

**Issue by SzotsGabor** [JENebel/Cadabra#2]
I was asked at TalkChess to share an exe of Cadabra, which I did. As you can see, some, I'd say most, people can't build exes from sources. So if you are open to let them play with your engine maybe you should consider releasing not only the sources but  also exes for a couple of platforms (32-bit, old 64-bit, modern).

PS. Your engine is now on the CCRL blitz list. Unfortunately much weaker than you expected but I can see from the great number of commits that you are very actively developing it.

**Comment by JENebel** [comment]
I am planning to compile and release exes at some point soon. I'm no expert at doing it right, so thats why it is a little delayed.

It is great to see Cadabra featured on the list, no matter the rating! I had just run a lot of very short games against some other engines to get a rough strength estimate. This was unfortunately not very accurate, but it will improve in future versions!
